"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { signIn, signUp } from "@/lib/auth-client"
import { Zap, Loader2 } from "lucide-react"

export function AuthForm({ mode }: { mode: "sign-in" | "sign-up" }) {
  const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setLoading(true); const result = mode === "sign-in" ? await signIn.email({ email, password }) : await signUp.email({ email, password, name }); setLoading(false); if (result.error) { setError("We could not complete that request. Check your details and try again."); return }; router.push("/"); router.refresh() }
  return <main className="flex min-h-screen items-center justify-center bg-background px-4"><div className="w-full max-w-md"><div className="mb-8 flex items-center justify-center gap-3"><div className="flex size-10 items-center justify-center rounded-md bg-primary text-primary-foreground"><Zap className="size-5" /></div><div><p className="font-mono text-lg font-semibold">UtilBill</p><p className="text-xs text-muted-foreground">Utility billing console</p></div></div><section className="rounded-xl border border-border bg-card p-6 shadow-sm"><div className="mb-6 space-y-1"><h1 className="text-xl font-semibold">{mode === "sign-in" ? "Sign in to your workspace" : "Create your workspace account"}</h1><p className="text-sm text-muted-foreground">Access is managed by your utility operations team.</p></div><form onSubmit={submit} className="space-y-4">{mode === "sign-up" && <label className="block space-y-1.5 text-sm"><span>Full name</span><input required value={name} onChange={(e) => setName(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3" /></label>}<label className="block space-y-1.5 text-sm"><span>Email</span><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3" /></label><label className="block space-y-1.5 text-sm"><span>Password</span><input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3" /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<button disabled={loading} className="flex h-10 w-full items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-60">{loading && <Loader2 className="size-4 animate-spin" />}{mode === "sign-in" ? "Sign in" : "Create account"}</button></form><p className="mt-5 text-center text-sm text-muted-foreground">{mode === "sign-in" ? "New to UtilBill?" : "Already have an account?"} <Link className="font-medium text-primary hover:underline" href={mode === "sign-in" ? "/sign-up" : "/sign-in"}>{mode === "sign-in" ? "Create an account" : "Sign in"}</Link></p></section></div></main>
}
